AWSTemplateFormatVersion: '2010-09-09'

Description: >

    The general template for InfraVpc. 

Mappings:
    AWSRegionToEC2AMI:
        us-west-2:
            AMI: ami-bd7beddd
        eu-west-2:
            AMI: ami-f1949e95


Resources:

    Vpc:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/${CFS3Name}/infra-vpc/components/Vpc.yaml
            Parameters:
                EnvironmentName:           !Ref EnvironmentName
                VpcCIDR:                   !Ref VpcCIDR
                PublicSubnet1CIDR:         !Ref PublicSubnet1CIDR
                PublicSubnet2CIDR:         !Ref PublicSubnet2CIDR
                PrivateSubnet1CIDR:        !Ref PrivateSubnet1CIDR
                PrivateSubnet2CIDR:        !Ref PrivateSubnet2CIDR
                # PeerVpcCIDRGhMisc:          !Ref PeerVpcCIDRGhMisc
                # VPCPeeringConnectionGhMisc: !Ref VPCPeeringConnectionGhMisc
                # PeerVpcCIDRGames:           !Ref PeerVpcCIDRGames
                # VPCPeeringConnectionGames:  !Ref VPCPeeringConnectionGames
                VpnAsLux:                   !Ref VpnAsLux
                VpnIpLux:                   !Ref VpnIpLux

    Bastion:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/${CFS3Name}/infra-vpc/components/Bastion.yaml
            Parameters:
                VPCid:                      !GetAtt Vpc.Outputs.VpcId
                SshFrom1:                   !Ref SshFrom1
                SshFrom2:                   !Ref SshFrom2
                SshFrom3:                   !Ref SshFrom3
                SshFrom4:                   !Ref SshFrom4
                KeyName:                    !Ref KeyName
                BastionHostInstanceType:    !Ref BastionHostInstanceType
                PublicSubnet1Id:            !GetAtt Vpc.Outputs.PublicSubnet1Id


Parameters:

    CFS3Name:
        Description: S3 bucket name with CF components
        Type: String

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        Default: dev

    VpcCIDR:
        Description: Please enter the IP range (CIDR notation) for this VPC
        Type: String
        Default: 10.51.0.0/24

    PublicSubnet1CIDR:
        Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
        Type: String
        Default: 10.51.0.0/26

    PublicSubnet2CIDR:
        Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
        Type: String
        Default: 10.51.0.64/26

    PrivateSubnet1CIDR:
        Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
        Type: String
        Default: 10.51.0.128/26

    PrivateSubnet2CIDR:
        Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
        Type: String
        Default: 10.51.0.192/26

    SshFrom1:
        Description: IP address to grant access to
        Type: String
        MinLength: 9
        MaxLength: 18
        AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
        ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
        Default: 212.67.170.162/32

    SshFrom2:
        Description: IP address to grant access to
        Type: String
        MinLength: 9
        MaxLength: 18
        AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
        ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
        Default: 127.0.0.1/32

    SshFrom3:
        Description: IP address to grant access to
        Type: String
        MinLength: 9
        MaxLength: 18
        AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
        ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
        Default: 127.0.0.2/32

    SshFrom4:
        Description: IP address to grant access to
        Type: String
        MinLength: 9
        MaxLength: 18
        AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
        ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
        Default: 127.0.0.3/32

    # PeerVpcCIDRGhMisc:
    #     Description: Please enter the IP range (CIDR notation) for peering VPC
    #     Type: String
    #     Default: 10.51.0.0/24

    # VPCPeeringConnectionGhMisc:
    #     Description: Please enter the ID of the peering VPC
    #     Type: String
    #     Default: none

    # PeerVpcCIDRGames:
    #     Description: Please enter the IP range (CIDR notation) for peering VPC
    #     Type: String
    #     Default: 10.51.3.0/24

    # VPCPeeringConnectionGames:
    #     Description: Please enter the ID of the peering VPC
    #     Type: String
    #     Default: none

    VpnAsLux:
        Description: IpSec As for Lux
        Type: String
        Default: none

    VpnIpLux:
        Description: IP address of Lux IpSec endpoint
        Type: String
        Default: none

    KeyName:
        ConstraintDescription: must be the name of an existing EC2 KeyPair.
        Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
        MinLength: '1'
        Type: AWS::EC2::KeyPair::KeyName

    BastionHostInstanceType:
        Type: String
        Default: t2.micro
        AllowedValues:
            - t2.micro
            - t2.small
            - m1.small
        Description: Enter t2.micro, t2.small, or m1.small. Default is t2.micro.                

Outputs:

    VpcId:
        Description: The ID for the created VPC 
        Value: !GetAtt Vpc.Outputs.VpcId

    PublicSubnets:
        Description: A list of the public subnets
        Value: !Join [ ",", [ !GetAtt Vpc.Outputs.PublicSubnet1Id, !GetAtt Vpc.Outputs.PublicSubnet2Id ]]

    PublicSubnet1Id: 
        Description: The ID for 1 public subnet
        Value: !GetAtt Vpc.Outputs.PublicSubnet1Id

    PublicSubnet2Id: 
        Description: The ID for 2 public subnet
        Value: !GetAtt Vpc.Outputs.PublicSubnet2Id

    PrivateSubnets:
        Description: A list of the private subnets
        Value: !Join [ ",", [ !GetAtt Vpc.Outputs.PrivateSubnet1Id, !GetAtt Vpc.Outputs.PrivateSubnet2Id ]]

    PrivateSubnet1Id: 
        Description: The ID for 1 private subnet
        Value: !GetAtt Vpc.Outputs.PrivateSubnet1Id

    PrivateSubnet2Id: 
        Description: The ID for 2 private subnet
        Value: !GetAtt Vpc.Outputs.PrivateSubnet2Id

    PublicRouteTable:
        Description: The route table for public subnets
        Value: !GetAtt Vpc.Outputs.PublicRouteTable

    PrivateRouteTable1:
        Description: The route table for private subnet in AZ1
        Value: !GetAtt Vpc.Outputs.PrivateRouteTable1

    PrivateRouteTable2:
        Description: The route table for private subnet in AZ2
        Value: !GetAtt Vpc.Outputs.PrivateRouteTable2
    EIP:
        Description: Elsatic IP for Bastion
        Value: !GetAtt Vpc.Outputs.EIP
        
    BastionIp:
        Description: The route table for private subnet in AZ2
        Value: !GetAtt Bastion.Outputs.BastionIp

    BastionSecurityGroup:
        Description: The route table for private subnet in AZ2
        Value: !GetAtt Bastion.Outputs.BastionSecurityGroup