AWSTemplateFormatVersion: '2010-09-09'

Description: >

    The general template for GamesVpc. 

Mappings:
    AWSRegionToEC2DefaultAMI:
        us-west-2:
            AMI: ami-bd7beddd
    AWSRegionToEC2FastlaneAMI:    
        us-west-2:
            AMI: ami-e0bc2980
    AWSRegionToEC2StudioJenkinsAMI:    
        us-west-2:
            AMI: ami-5cbf2f3c   

Resources:

    Vpc:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/${CFS3Name}/vpc-games/components/Vpc.yaml
            Parameters:
                EnvironmentName:           !Ref EnvironmentName
                VpcCIDR:                   !Ref VpcCIDR
                PublicSubnet1CIDR:         !Ref PublicSubnet1CIDR
                PublicSubnet2CIDR:         !Ref PublicSubnet2CIDR
                PrivateSubnet1CIDR:        !Ref PrivateSubnet1CIDR
                PrivateSubnet2CIDR:        !Ref PrivateSubnet2CIDR
                InfraVpcId:                !Ref InfraVpcId
                InfraVpcCIDR:              !Ref InfraVpcCIDR         

    Fastlane:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/${CFS3Name}/vpc-games/components/Fastlane.yaml
            Parameters:
                InfraVpcCIDR:               !Ref InfraVpcCIDR
                VPCid:                      !GetAtt Vpc.Outputs.VpcId
                KeyName:                    !Ref KeyName
                FastlaneHostInstanceType:   !Ref FastlaneHostInstanceType
                PublicSubnet1Id:           !GetAtt Vpc.Outputs.PublicSubnet1Id
                S3BucketAssetsName:         !Ref S3BucketAssetsName
                DaysToIAAssets:             !Ref DaysToIAAssets
                DaysToGLACIERAssets:        !Ref DaysToGLACIERAssets
                AppUserName:                !Ref AppUserName
                IAMRoleFastlaneArn:         !Ref IAMRoleFastlaneArn
                AccountId:                  !Ref AccountId


    Studios:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/${CFS3Name}/vpc-games/components/Studios.yaml
            Parameters:
                    StudioTemplateHttpsFrom1:              !Ref StudioTemplateHttpsFrom1
                    StudioTemplateHttpsFrom2:              !Ref StudioTemplateHttpsFrom2
                    StudioTemplateHttpsFrom3:              !Ref StudioTemplateHttpsFrom3
                    StudioTemplateHttpsFrom4:              !Ref StudioTemplateHttpsFrom4
                    VPCid:                  !GetAtt Vpc.Outputs.VpcId
                    InfraVpcCIDR:           !Ref InfraVpcCIDR
                    PublicSubnet1Id:        !GetAtt Vpc.Outputs.PublicSubnet1Id
                    PrivateSubnet1Id:        !GetAtt Vpc.Outputs.PrivateSubnet1Id
                    ApachePort:             !Ref ApachePort
                    GhosSslCert:            !Ref GhosSslCert
                    KeyName:                !Ref KeyName
                    StudioTemplateGitRepoName: !Ref StudioTemplateGitRepoName
                    CFS3Name:                   !Ref CFS3Name

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        Default: dev

    VpcCIDR:
        Description: Please enter the IP range (CIDR notation) for this VPC
        Type: String
        Default: 10.51.3.0/24

    PublicSubnet1CIDR:
        Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
        Type: String
        Default: 10.51.3.0/26

    PublicSubnet2CIDR:
        Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
        Type: String
        Default: 10.51.3.64/26

    PrivateSubnet1CIDR:
        Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
        Type: String
        Default: 10.51.3.128/26

    PrivateSubnet2CIDR:
        Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
        Type: String
        Default: 10.51.3.192/26

    InfraVpcId:
        Description: Please enter the Id of InfraVpc
        Type: String
        Default: vpc-a23e58c5
    
    InfraVpcCIDR:
        Description: Please enter the IP range (CIDR notation) for INFRA VPC
        Type: String
        Default: 10.51.2.0/24

    FastlaneHostInstanceType:
        Type: String
        Default: t2.small
        AllowedValues:
            - t2.small
            - t2.medium 
            - m4.large
        Description: Enter t2.small, t2.medium or m4.large. Default is t2.small.

    KeyName:
        ConstraintDescription: must be the name of an existing EC2 KeyPair.
        Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
        MinLength: '1'
        Type: AWS::EC2::KeyPair::KeyName

    S3BucketAssetsName:
        Description: Name of Bucket for Assets
        Type: String

    DaysToIAAssets:
        Description: Days before file moved to IA storage
        Type: Number
        Default: 30

    DaysToGLACIERAssets:
        Description: Days before file moved to Glacier
        Type: Number
        Default: 90

    AppUserName:
        Description: User name for parser app
        Type: String

    ApachePort:
        Description: Apache port in front of Jenkins's app
        Type: String
        MinLength: 2
        MaxLength: 5
        Default: 80

    GhosSslCert:
        Description: arn of SSL cert
        Type: String
        Default: arn:aws:acm:us-west-2:777556643132:certificate/8ea61a4f-1549-4703-b99f-da25a2be8f7d

    IAMRoleFastlaneArn:
        Description: temp
        Type: String

    StudioTemplateHttpsFrom1:
        Description: IP address to grant access to
        Type: String
        MinLength: 9
        MaxLength: 18
        AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
        ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
        Default: 212.67.170.162/32

    StudioTemplateHttpsFrom2:
        Description: IP address to grant access to
        Type: String
        MinLength: 9
        MaxLength: 18
        AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
        ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
        Default: 127.0.0.1/32

    StudioTemplateHttpsFrom3:
        Description: IP address to grant access to
        Type: String
        MinLength: 9
        MaxLength: 18
        AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
        ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
        Default: 127.0.0.2/32

    StudioTemplateHttpsFrom4:
        Description: IP address to grant access to
        Type: String
        MinLength: 9
        MaxLength: 18
        AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
        ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
        Default: 127.0.0.3/32
    
    CFS3Name:
        Description: S3 bucket name with CF components
        Type: String

    AccountId:
        Type: String

    StudioTemplateGitRepoName:
        Type: String

Outputs:

    VpcId:
        Description: The ID for the created VPC 
        Value: !GetAtt Vpc.Outputs.PrivateSubnet1Id

    PublicSubnets:
        Description: A list of the public subnets
        Value: !Join [ ",", [ !GetAtt Vpc.Outputs.PublicSubnet1Id, !GetAtt Vpc.Outputs.PublicSubnet2Id ]]

    PublicSubnet1Id: 
        Description: The ID for 1 public subnet
        Value: !GetAtt Vpc.Outputs.PublicSubnet1Id

    PublicSubnet2Id: 
        Description: The ID for 2 public subnet
        Value: !GetAtt Vpc.Outputs.PublicSubnet2Id

    PrivateSubnets:
        Description: A list of the private subnets
        Value: !Join [ ",", [ !GetAtt Vpc.Outputs.PrivateSubnet1Id, !GetAtt Vpc.Outputs.PrivateSubnet2Id ]]

    PrivateSubnet1Id: 
        Description: The ID for 1 private subnet
        Value: !GetAtt Vpc.Outputs.PrivateSubnet1Id

    PrivateSubnet2Id: 
        Description: The ID for 2 private subnet
        Value: !GetAtt Vpc.Outputs.PrivateSubnet2Id

    PublicRouteTable:
        Description: The route table for public subnets
        Value: !GetAtt Vpc.Outputs.PublicRouteTable

    PrivateRouteTable1:
        Description: The route table for private subnet in AZ1
        Value: !GetAtt Vpc.Outputs.PrivateRouteTable1

    PrivateRouteTable2:
        Description: The route table for private subnet in AZ2
        Value: !GetAtt Vpc.Outputs.PrivateRouteTable2

    VPCPeeringConnectionId:
        Description: The ID for VPC peering to InfraVpc
        Value: !GetAtt Vpc.Outputs.VPCPeeringConnectionId

    JenkinsStudioTemplateBalanserId: 
        Value: !GetAtt Studios.Outputs.JenkinsStudioTemplateBalanserId

    FastlaneEC2InstanceId: 
        Value: !GetAtt Fastlane.Outputs.FastlaneEC2InstanceId

    FastlaneAppUserName:
        Value: !GetAtt Fastlane.Outputs.AppUserName

    S3BucketAssetsName:
        Value: !GetAtt Fastlane.Outputs.S3BucketAssetsName

    S3BucketAssetsId:
        Value: !GetAtt Fastlane.Outputs.S3BucketAssetsId

    StudioTemplateGitRepoName:
        Value: !GetAtt Studios.Outputs.StudioTemplateGitRepoName

    StudioTemplateGitRepoId:
        Value: !GetAtt Studios.Outputs.StudioTemplateGitRepoId

    StudioTemplateGitRepoArn:
        Value: !GetAtt Studios.Outputs.StudioTemplateGitRepoArn

    StudioTemplateGitRepoUrlHttp:
        Value: !GetAtt Studios.Outputs.StudioTemplateGitRepoUrlHttp

    StudioTemplateGitRepoUrlSsh:
        Value: !GetAtt Studios.Outputs.StudioTemplateGitRepoUrlSsh

    LBSecurityGroupJenkinsStudioTemplateId:
        Value: !GetAtt Studios.Outputs.LBSecurityGroupJenkinsStudioTemplateId

    EC2SecurityGroupJenkinsStudioTemplateId:
        Value: !GetAtt Studios.Outputs.EC2SecurityGroupJenkinsStudioTemplateId

    DNSNameJenkinsStudioTemplate:
        Value: !GetAtt Studios.Outputs.DNSNameJenkinsStudioTemplate  