AWSTemplateFormatVersion: '2010-09-09'

Description: >

  Git Repo for a test Studio "Bullet-tooth Tony"

Parameters:

    StudioTemplateGitRepoName:
        Type: String

Resources:

    StudioTemplateGitRepo:
        Type: "AWS::CodeCommit::Repository"
        Properties: 
          RepositoryName: !Ref StudioTemplateGitRepoName

    StudioTemplateGroup:
        Type: "AWS::IAM::Group"
        Properties:
            GroupName: "StudioTemplateGeneralGroup"
            Policies:
                - PolicyName: 'StudioTemplateGeneralPolicy'
                  PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                    - Effect: Allow
                      Action:
                      - 'codecommit:*'
                      Resource: 
                      - !GetAtt StudioTemplateGitRepo.Arn

Outputs:

    StudioTemplateGitRepoName:
        Value: !Ref StudioTemplateGitRepoName

    StudioTemplateGitRepoId:
        Value: !Ref StudioTemplateGitRepo

    StudioTemplateGitRepoArn:
        Value: !GetAtt StudioTemplateGitRepo.Arn

    StudioTemplateGitRepoUrlHttp:
        Value: !GetAtt StudioTemplateGitRepo.CloneUrlHttp

    StudioTemplateGitRepoUrlSsh:
        Value: !GetAtt StudioTemplateGitRepo.CloneUrlSsh