AWSTemplateFormatVersion: '2010-09-09'

Description: >

  Git Repo for a test Studio "Bullet-tooth Tony"

Parameters:

    StudioTemplateGitRepoName:
        Type: String

Resources:

    StudioTemplateGitRepo:
        Type: "AWS::CodeCommit::Repository"
        Properties: 
          RepositoryName: !Ref StudioTemplateGitRepoName

    StudioTemplateGeneralGroup:
        Type: "AWS::IAM::Group"
        Properties:
            GroupName: "CBS-StudioTemplate-GeneralGroup"
            Policies:
                - PolicyName: 'StudioTemplate-GeneralPolicy'
                  PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                    - Effect: Allow
                      Action:
                      - 'codecommit:*'
                      Resource: 
                      - !GetAtt StudioTemplateGitRepo.Arn

    StudioTemplateGeneralGroupAssociation:
        Type: "AWS::IAM::UserToGroupAddition"
        Properties: 
            GroupName: "CBS-StudioTemplate-GeneralGroup"
            Users:
                - adm-kirillk

    UserTest:
        Type: "AWS::IAM::User"
        Properties: 
            Groups:
                - !Ref StudioTemplateGeneralGroupAssociation
            UserName: test        



Outputs:

    StudioTemplateGitRepoName:
        Value: !Ref StudioTemplateGitRepoName

    StudioTemplateGitRepoId:
        Value: !Ref StudioTemplateGitRepo

    StudioTemplateGitRepoArn:
        Value: !GetAtt StudioTemplateGitRepo.Arn

    StudioTemplateGitRepoUrlHttp:
        Value: !GetAtt StudioTemplateGitRepo.CloneUrlHttp

    StudioTemplateGitRepoUrlSsh:
        Value: !GetAtt StudioTemplateGitRepo.CloneUrlSsh