


Resources:

    ChefEC2Instance: 
        Type: "AWS::EC2::Instance"
        Properties: 
            ImageId: !FindInMap [AWSRegionToEC2AMI, !Ref 'AWS::Region', AMI]
            KeyName: !Ref KeyName
            IamInstanceProfile: !Ref ChefInstanceProfile
            InstanceType: !Ref ChefHostInstanceType
            SecurityGroupIds: [!Ref ChefEC2SecurityGroup]
            SubnetId: !Ref PrivateSubnet1 
            Tags:
              - Key: Name
                Value: InfraChef

    ChefInstanceProfile:
        Type: 'AWS::IAM::InstanceProfile'
        Properties:
          Path: '/'
          Roles:
          - !Ref ChefIAMRole

    ChefEC2SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Enable access to the Chef EC2
            VpcId: !Ref VPC
            SecurityGroupIngress:
              - IpProtocol: tcp
                FromPort: 22
                ToPort: 22
                SourceSecurityGroupId: !Ref BastionSecurityGroup
              - IpProtocol: tcp
                FromPort: 80
                ToPort: 80
                CidrIp: 10.50.0.0/16
              - IpProtocol: tcp
                FromPort: 443
                ToPort: 443
                CidrIp: 10.50.0.0/16
            Tags:
                - Key: Name
                  Value: infra-chef-ec2

    ChefIAMRole:
        Type: 'AWS::IAM::Role'
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Principal:
                Service:
                - 'ec2.amazonaws.com'
              Action:
              - 'sts:AssumeRole'
          Path: '/'
          Policies:
          - PolicyName: 'ec2'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: Allow
                Action:
                - 'ec2:AssociateAddress'
                Resource:
                - '*'
          - PolicyName: logs
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: Allow
                Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
                - 'logs:DescribeLogStreams'
                Resource:
                - 'arn:aws:logs:*:*:*'



Parameters:

      ChefHostInstanceType:
        Type: String
        Default: t2.small
        AllowedValues:
            - t2.small
            - t2.medium 
            - m4.large
        Description: Enter t2.small, t2.medium or m4.large. Default is t2.small. 