AWSTemplateFormatVersion: '2010-09-09'

Description: >

    Account setting: CloudTrail

Resources:

  Trail:
    Type: "AWS::CloudTrail::Trail"
    Properties:
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true
      S3BucketName: !Ref S3Bucket

  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3BucketName
      LifecycleConfiguration: 
        Rules:
        - 
          Id: !Sub ${DaysToIA}toIA${DaysToGLACIER}toGLACIER
          Status: "Enabled"
          Transitions:
          -
            StorageClass: "STANDARD_IA"
            TransitionInDays: !Ref DaysToIA
          -
            StorageClass: "GLACIER"
            TransitionInDays: !Ref DaysToGLACIER



  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - 
            Action:
              - "s3:*"
            Effect:  "Allow"
            Resource: !Sub arn:aws:s3:::${S3BucketName}
            Principal:  "*"
          - 
            Action:
              - "s3:PutObject"
            Effect:  "Allow"
            Resource: !Sub arn:aws:s3:::${S3BucketName}/*
            Principal:
              Service: 
              - "cloudtrail.amazonaws.com"

Parameters:

  S3BucketName:
    Description: Name of Bucket for logs
    Type: String

  DaysToIA:
    Description: Days before file moved to IA storage
    Type: Number
    Default: 30

  DaysToGLACIER:
    Description: Days before file moved to Glacier
    Type: Number
    Default: 90


Outputs:
  
  S3BucketName:
    Description: Name of Bucket for logs
    Value: !Ref S3BucketName

  Trail:
    Description: Trail tread for logs
    Value: !Ref Trail

  S3BucketPolicy:
    Description: Bucket Policy
    Value: !Ref S3BucketPolicy

  DaysToIA:
    Description: Days before file moved to IA storage
    Value: !Ref DaysToIA
  
  DaysToGLACIER:
    Description: Days before file moved to IA storage
    Value: !Ref DaysToGLACIER






