AWSTemplateFormatVersion: '2010-09-09'

Description: >
   This template takes care about DNS

Resources:

  InternalProdHostedZone:
      Type: "AWS::Route53::HostedZone"
      Properties:
           HostedZoneConfig:
               Comment: "Internal DNS"
           Name: !Ref InterlnalProdHostedZoneName
           VPCs:
            -
              VPCId: !Ref VpcInfra
              VPCRegion: "us-west-2"
            -
              VPCId: !Ref VpcGames
              VPCRegion: "us-west-2"
            -
              VPCId: !Ref VpcMobile
              VPCRegion: "us-west-2"   
            -
              VPCId: !Ref VpcGhMisc
              VPCRegion: "us-west-2" 
           
  InternalProdHostedZoneRecord1:
      Type: AWS::Route53::RecordSet
      Properties:
          HostedZoneId: !Ref InternalProdHostedZone
          Comment: "Interl DNS for Chef server"
          Name: "chef.us-west-2.777556643132.gamehouseos.internal."
          Name: !Join ['', ['chef', ., !Ref InterlnalProdHostedZoneName]]
          Type: A
          TTL: '900'
          ResourceRecords:
          - '10.50.2.186'
          
Parameters:

  InterlnalProdHostedZoneName:
       Type: String
       Description: "The DNS name of an existing Amazon Route 53 hosted zone"

  VpcInfra:
      Type: String

  VpcGames:
      Type: String

  VpcMobile:
      Type: String

  VpcGhMisc:
      Type: String

  
Outputs:

      InternalProdHostedZoneRecord1:
        Value: !Ref InternalProdHostedZoneRecord1

