AWSTemplateFormatVersion: '2010-09-09'

Description: >

    Fastlane EC2, S3 for assets

Mappings:
    AWSRegionToEC2DefaultAMI:
        us-west-2:
            AMI: ami-bd7beddd
    AWSRegionToEC2FastlaneAMI:    
        us-west-2:
            AMI: ami-38d34b58
    AWSRegionToEC2StudioJenkinsAMI:    
        us-west-2:
            AMI: ami-5cbf2f3c 

Parameters:

    InfraVpcCIDR:
        Description: Please enter the IP range (CIDR notation) for INFRA VPC
        Type: String
        Default: 10.51.2.0/24

    VPCid:
        Description: Please enter the IP range (CIDR notation) for INFRA VPC
        Type: String
        Default: 10.51.2.0/24

    KeyName:
        ConstraintDescription: must be the name of an existing EC2 KeyPair.
        Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
        MinLength: '1'
        Type: AWS::EC2::KeyPair::KeyName

    FastlaneHostInstanceType:
        Type: String
        Default: t2.small
        AllowedValues:
            - t2.small
            - t2.medium 
        Description: Enter t2.small, t2.medium or m4.large. Default is t2.small.

    PublicSubnet1Id:
        Type: String
        Default: 10.51.2.0/24

    S3BucketAssetsName:
        Description: Name of Bucket for Assets
        Type: String

    DaysToIAAssets:
        Description: Days before file moved to IA storage
        Type: Number
        Default: 30

    DaysToGLACIERAssets:
        Description: Days before file moved to Glacier
        Type: Number
        Default: 90

    AppUserName:
        Description: User name for parser app
        Type: String

    IAMRoleFastlaneArn:
        Description: temp
        Type: String

    AccountId:
        Type: String


Resources:

    EC2SecurityGroupFastlane:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Fastlane SG
            VpcId: !Ref VPCid
            SecurityGroupIngress:
              - IpProtocol: tcp
                FromPort: 22
                ToPort: 22
                CidrIp: !Ref InfraVpcCIDR
            Tags:
                - Key: Name
                  Value: games-fastlane-ec2

    FastlaneEC2Instance: 
            Type: "AWS::EC2::Instance"
            Properties: 
              ImageId: !FindInMap [AWSRegionToEC2FastlaneAMI, !Ref 'AWS::Region', AMI]
              KeyName: !Ref KeyName
              IamInstanceProfile: !Ref InstanceProfileFastlane
              InstanceType: !Ref FastlaneHostInstanceType
              SecurityGroupIds: [!Ref EC2SecurityGroupFastlane]
              SubnetId: !Ref PublicSubnet1Id
              Tags:
                - Key: Name
                  Value: GamesFastlane

    InstanceProfileFastlane:
        Type: 'AWS::IAM::InstanceProfile'
        Properties:
          Path: '/'
          Roles:
          - !Ref IAMRoleFastlane

    IAMRoleFastlane:
        Type: 'AWS::IAM::Role'
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Principal:
                Service:
                - 'ec2.amazonaws.com'
              Action:
              - 'sts:AssumeRole'
          Path: '/'
          Policies:

          - PolicyName: 'logs'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: Allow
                Action:
                - 'logs:*'
                Resource:
                - 'arn:aws:logs:*:*:*'

          - PolicyName: 'S3BucketAssetsDownloadOnly'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: Allow
                Action:
                    - "s3:GetObject"
                    - "s3:GetObjectVersion"
                Resource:
                - !Sub arn:aws:s3:::${S3BucketAssetsName}/*
              - Effect: Allow
                Action:
                    - "s3:ListBucket"
                Resource:
                - !Sub arn:aws:s3:::${S3BucketAssetsName}/

    S3BucketAssets:
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: !Ref S3BucketAssetsName
            LifecycleConfiguration: 
                Rules:
                - 
                    Id: !Sub ${DaysToIAAssets}toIA${DaysToGLACIERAssets}toGLACIER
                    Status: "Enabled"
                    Transitions:
                    -
                        StorageClass: "STANDARD_IA"
                        TransitionInDays: !Ref DaysToIAAssets
                    -
                        StorageClass: "GLACIER"
                        TransitionInDays: !Ref DaysToGLACIERAssets

    S3BucketAssetsPolicy:   
        Type: "AWS::S3::BucketPolicy"
        Properties:
            Bucket: !Ref S3BucketAssets
            PolicyDocument:
                Statement:
                    - 
                        Action:
                            - "s3:ListBucket"
                        Effect:  "Allow"
                        Resource: !Sub arn:aws:s3:::${S3BucketAssetsName}
                        Principal: 
                            AWS: 
                            - !Sub arn:aws:iam::${AccountId}:user/${IAMAppUser}

                    - 
                        Action:
                            - "s3:PutObject"
                        Effect:  "Allow"
                        Resource: !Sub arn:aws:s3:::${S3BucketAssetsName}/*
                        Principal:
                            AWS: 
                            - !Sub arn:aws:iam::${AccountId}:user/${IAMAppUser}
                         
                    - 
                        Action:
                            - "s3:ListBucket"
                        Effect:  "Allow"
                        Resource: !Sub arn:aws:s3:::${S3BucketAssetsName}
                        Principal: 
                            AWS: 
                            - !Ref IAMRoleFastlaneArn
                    - 
                        Action:
                            - "s3:GetObject"
                            - "s3:GetObjectVersion"
                        Effect:  "Allow"
                        Resource: !Sub arn:aws:s3:::${S3BucketAssetsName}/*
                        Principal:
                            AWS: 
                            - !Ref IAMRoleFastlaneArn

    IAMAppUser:
        Type: 'AWS::IAM::User'
        Properties:
            UserName: !Ref AppUserName
            Path: '/'
            Policies:
            - PolicyName: 'S3BucketAssetsInsert'
              PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                    - Effect: Allow
                      Action:
                        - "s3:PutObject"
                      Resource:
                        - !Sub arn:aws:s3:::${S3BucketAssetsName}/*
                    - Effect: Allow
                      Action:
                        - "s3:ListBucket"
                      Resource:
                        - !Sub arn:aws:s3:::${S3BucketAssetsName}/

Outputs:

    FastlaneEC2Instanced: 
        Value: !Ref FastlaneEC2Instance

    AppUserName:
        Value: !Ref AppUserName

    S3BucketAssetsName:
        Value: !Ref S3BucketAssetsName

    S3BucketAssetsId:
        Value: !Ref S3BucketAssets