AWSTemplateFormatVersion: '2010-09-09'

Description: >

  The top level template for whole project "Build street"


Parameters:

    #Shared parameters
    CFS3Name:
        Description: S3 bucket name with CF components
        Type: String

    #TemplateStudio
    StudioTemplateHttpsFrom1:
        Type: String
    
    StudioTemplateHttpsFrom2:
        Type: String

    StudioTemplateHttpsFrom3:
        Type: String

    StudioTemplateHttpsFrom4:
        Type: String

    VPCid:
        Type: String

    InfraVpcCIDR:
        Type: String

    PublicSubnet1Id:
        Type: String

    ApachePort:
        Type: String

    GhosSslCert:
        Type: String

    KeyName:
        ConstraintDescription: must be the name of an existing EC2 KeyPair.
        MinLength: '1'
        Type: AWS::EC2::KeyPair::KeyName

    StudioTemplateGitRepoName:
        Type: String

Resources:

    TemplateStudio:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/${CFS3Name}/vpc-games/components/studios/TemplateStudio.yaml
            Parameters:
                StudioTemplateGitRepoName:                !Ref StudioTemplateGitRepoName
                HttpsFrom1:                               !Ref StudioTemplateHttpsFrom1
                HttpsFrom2:                               !Ref StudioTemplateHttpsFrom2                
                HttpsFrom3:                               !Ref StudioTemplateHttpsFrom3
                HttpsFrom4:                               !Ref StudioTemplateHttpsFrom4
                VPCid:                                    !Ref VPCid
                InfraVpcCIDR:                             !Ref InfraVpcCIDR
                PublicSubnet1Id:                          !Ref PublicSubnet1Id
                ApachePort:                               !Ref ApachePort
                GhosSslCert:                              !Ref GhosSslCert
                KeyName:                                  !Ref KeyName
                CFS3Name:                                 !Ref CFS3Name


Outputs:

    #TemplateStudio
    LBSecurityGroupJenkinsStudioTemplateId:
        Value: !GetAtt TemplateStudio.Outputs.LBSecurityGroupJenkinsStudioTemplateId

    EC2SecurityGroupJenkinsStudioTemplateId:
        Value: !GetAtt TemplateStudio.Outputs.EC2SecurityGroupJenkinsStudioTemplate

    JenkinsStudioTemplateEC2InstanceId: 
        Value: !GetAtt TemplateStudio.Outputs.JenkinsStudioTemplateEC2InstanceId

    JenkinsStudioTemplateBalanserId: 
        Value: !GetAtt TemplateStudio.Outputs.JenkinsStudioTemplateBalanser

    StudioTemplateGitRepoName:
        Value: !GetAtt TemplateStudio.Outputs.StudioTemplateGitRepoName

    StudioTemplateGitRepoId:
        Value: !GetAtt TemplateStudio.Outputs.StudioTemplateGitRepoId

    StudioTemplateGitRepoArn:
        Value: !GetAtt TemplateStudio.Outputs.StudioTemplateGitRepoArn

    StudioTemplateGitRepoUrlHttp:
        Value: !GetAtt TemplateStudio.Outputs.StudioTemplateGitRepoUrlHttp

    StudioTemplateGitRepoUrlSsh:
        Value: !GetAtt TemplateStudio.Outputs.StudioTemplateGitRepoUrlSsh



